clients:
  - url: http://loki:3100/loki/api/v1/push

positions:
  filename: /var/log/positions.yaml

scrape_configs:
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs
          __path__: /var/log/auth.log
